[package]
name = "mrsbfh"
version = "0.1.0"
authors = ["MTRNord <mtrnord1@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies.matrix-sdk]
git = "https://github.com/matrix-org/matrix-rust-sdk.git"
rev = "4f2cad8f626068f05d567588d8398d0952536a46"

[dependencies]
url = "2.1.1"

thiserror = "1.0"

# Command macros
mrsbfh-macros = {path = "../mrsbfh-macros"}
const-concat = {git = "https://github.com/Vurich/const-concat", rev = "f836e77a4ecadf6a11994340fdcbbdadcdc4906d"}

tokio = { version = "0.2", features = ["full"] }
tracing = "0.1"

serde = "1.0"
serde_yaml = "0.8.13"
serde_json = "1"

pulldown-cmark = "0.8.0" # For generating the help text