[package]
name = "example-bot"
version = "0.1.0"
authors = ["MTRNord <mtrnord1@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies.matrix-sdk]
git = "https://github.com/matrix-org/matrix-rust-sdk.git"
rev = "b311a31c9ef942c357ceb16f07586246655191ce"

[dependencies]
mrsbfh = {path = "../mrsbfh"}
serde = "1.0"
tracing = "0.1"
tracing-subscriber = "0.2"
tracing-futures = "0.2.4"
tokio = { version = "1.0.1", features = ["full"] }
clap = "3.0.0-beta.2"
async-trait = "0.1.41"